///////////////////////////////////////////////////////////
//  EFileLoadStatus.cs
//  Implementation of the Enumeration EFileLoadStatus
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:23 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FileControler_Project.Enums
{
    public enum EFileLoadStatus:int
    {
        Success,
        FileTypeNotSupported,
        WrongFileTypeSeleceted,
        PartialReadSuccess,
        InvalidFileStructure,
        OpeningFailed,
        DBWriteFailed,
        Failed,
        InvalidFileExtension,
        InvalidDateTime,
        FileNameConventionViolated
    }
}
