///////////////////////////////////////////////////////////
//  EGeoRecordStatus.cs
//  Implementation of the Enumeration EGeoRecordStatus
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:23 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace CacheControler_Project.Enums
{
    /// <summary>
    /// //Status geografskog zapisa
    /// </summary>
    public enum EGeoRecordStatus : int
    {

        GIDUsed,
        GNameUsed,
        GeoRecordUsed,
        GeoRecordFree

    }//end EGeoRecordStatus
}