
CREATE TABLE GEOGRAPHY_SUBSYSTEM
(
    GID         varchar(15) NOT NULL,
    GNAME       varchar(15) NOT NULL,
    
    CONSTRAINT GEOGRAPHY_SUBSYSTEM_PK PRIMARY KEY(GID)
);

CREATE TABLE EES
(
    RECID       integer NOT NULL,
    TIME_STAMP  varchar(15) NOT NULL,
    GID         varchar(15) NOT NULL,
    
    CONSTRAINT EES_PK PRIMARY KEY(RECID),
    CONSTRAINT TIME_PLACE_UQ UNIQUE (RECID, GID, TIME_STAMP)
);

CREATE TABLE CONSUMPTION
(
    CID         integer NOT NULL,
    MWH         integer NOT NULL,
    
    CONSTRAINT CONSUMPTION_PK PRIMARY KEY(CID)
);

CREATE TABLE CONSUMPTION_AUDIT
(
    AID         integer NOT NULL,
    DUPVAL      integer NOT NULL,
    
    CONSTRAINT CONSUMPTION_AUDIT_PK PRIMARY KEY(AID)
);

CREATE TABLE CONSUMPTION_AUDITED
(
    AID         integer NOT NULL,
    RECID       integer NOT NULL,

    CONSTRAINT CONSUMPTION_AUDITED_PK PRIMARY KEY (AID, RECID),
    
    CONSTRAINT CA_CC_FK FOREIGN KEY (AID) REFERENCES CONSUMPTION_AUDIT(AID),
    CONSTRAINT CA_EE_FK FOREIGN KEY (RECID) REFERENCES EES(RECID)
);

CREATE TABLE CONSUMPTION_RECORDED
(
    CID         integer NOT NULL,
    RECID       integer NOT NULL,
    
    CONSTRAINT CONSUMPTION_RECORDED_PK PRIMARY KEY (CID, RECID),
    
    CONSTRAINT CR_CC_FK FOREIGN KEY (CID) REFERENCES CONSUMPTION(CID),
    CONSTRAINT CR_EE_FK FOREIGN KEY (RECID) REFERENCES EES(RECID)
);
commit;