///////////////////////////////////////////////////////////
//  AuditRecord.cs
//  Implementation of the Class AuditRecord
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:22 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Common_Project.Classes
{
    public class AuditRecord
    {

        private string gID;
        private int[] hoursOut;
        private string timeStamp;

        public AuditRecord()
        {

        }

        ~AuditRecord()
        {

        }

        public string GID
        {
            get
            {
                return gID;
            }
            set
            {
                gID = value;
            }
        }

        public int[] HoursOut
        {
            get
            {
                return hoursOut;
            }
            set
            {
                hoursOut = value;
            }
        }

        public string TimeStamp
        {
            get
            {
                return timeStamp;
            }
            set
            {
                timeStamp = value;
            }
        }

    }//end AuditRecord
}