///////////////////////////////////////////////////////////
//  AuditRecord.cs
//  Implementation of the Class AuditRecord
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:22 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Common_Project.Classes
{
    public class AuditRecord
    {

        private string gID;
        private string timeStamp;
        private int dupVal;

        public AuditRecord()
        {

        }

        public AuditRecord(string gID, string timeStamp, int dupVal)
        {
            this.gID = gID;
            this.timeStamp = timeStamp;
            this.dupVal = dupVal;
        }

        ~AuditRecord()
        {

        }

        public string GID
        {
            get
            {
                return gID;
            }
            set
            {
                gID = value;
            }
        }

        public string TimeStamp
        {
            get
            {
                return timeStamp;
            }
            set
            {
                timeStamp = value;
            }
        }

        public int DupVal
        {
            get
            {
                return dupVal;
            }
            set
            {
                dupVal = value;
            }
        }

        public override string ToString()
        {
            string outStr = String.Format("Audit record GID: {0}\tTimeStamp: {1}\tType: ",gID, timeStamp);
            if(DupVal==-1)
            { outStr += "Miss"; }
            else
            {
                outStr += "Duplicate\tValue: " + DupVal;
            }
            return outStr;
        }

    }//end AuditRecord
}