///////////////////////////////////////////////////////////
//  ConsumptionRecord.cs
//  Implementation of the Class ConsumptionRecord
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:22 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Common_Project.Classes
{
    public class ConsumptionRecord
    {

        private string gID;
        private int mWh;
        private string timeStamp;

        public ConsumptionRecord()
        {
            gID = "";
            mWh = -1;
            timeStamp = "";
        }

        public ConsumptionRecord(string gID, int mWh, string timeStamp)
        {
            this.gID = gID;
            this.mWh = mWh;
            this.timeStamp= timeStamp;
        }

        ~ConsumptionRecord()
        {

        }

        public bool Equals(ConsumptionRecord mirror)
        {
            return  (this.gID==mirror.gID) && 
                    (this.mWh==mirror.mWh) && 
                    (this.timeStamp==mirror.timeStamp);
        }
        public string GID
        {
            get
            {
                return gID;
            }
            set
            {
                gID = value;
            }
        }

        public int MWh
        {
            get
            {
                return mWh;
            }
            set
            {
                mWh = value;
            }
        }

        public string TimeStamp
        {
            get
            {
                return timeStamp;
            }
            set
            {
                timeStamp = value;
            }
        }

        public override string ToString()
        {
            return string.Format("Consumption record GID: {0}, HOUR: {1}, LOAD: {2}", gID, timeStamp, mWh);
        }

        public bool IsWholeEmpty()
        {
            return !(mWh == -1 && gID == "" && timeStamp == "");
        }

        public int GetHour()
        {
            if (timeStamp[timeStamp.Length - 2] == '-') return Int32.Parse(String.Format("{0}", timeStamp[timeStamp.Length - 1]));
            return Int32.Parse(String.Format("{0}{1}", timeStamp[timeStamp.Length - 2], timeStamp[timeStamp.Length - 1]));
        }

    }//end ConsumptionRecord
}