///////////////////////////////////////////////////////////
//  DSpanGeoReq.cs
//  Implementation of the Class DSpanGeoReq
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:23 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Common_Project.Classes
{
    [Serializable]
    public class DSpanGeoReq
    {

        private string from;
        private string gName;
        private string till;

        public DSpanGeoReq(string gName, string from, string till)
        {
            this.from=from;
            this.gName=gName;
            this.till=till;
        }


        ~DSpanGeoReq()
        {

        }

        public string From
        {
            get
            {
                return from;
            }
            set
            {
                from = value;
            }
        }

        public string GName
        {
            get
            {
                return gName;
            }
            set
            {
                gName = value;
            }
        }

        public string Till
        {
            get
            {
                return till;
            }
            set
            {
                till = value;
            }
        }

        public bool IsComplete()
        {
            return this.from!="" && this.till!="" && this.gName!= "";
        }

        public override string ToString()
        {
            return String.Format("Search request From:\t{0} \tTill:\t{1} \tfor area:\t{2}", from, till, GName);
        }
    }//end DSpanGeoReq
}