///////////////////////////////////////////////////////////
//  IConsumptionDAO.cs
//  Implementation of the Interface IConsumptionDAO
//  Generated by Enterprise Architect
//  Created on:      07-May-2021 2:59:26 PM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common_Project.Classes;

public interface IConsumptionDAO:ICRUDDao<ConsumptionRecord, string>  {


	List<ConsumptionRecord> FindByCountry(string countryID);

	List<ConsumptionRecord> FindByCountryAndDate(string countryID, string targetTimestamp);

	List<ConsumptionRecord> FindByCountryAndDatespan(string gID, string fromTimestamp, string tillTimestamp);


	List<ConsumptionRecord> FindByGeographyAndAfterDate(string gID, string from);


	List<ConsumptionRecord> FindByGeographyAndBeforeDate(string targetGID, string targetTimestamp);


	ConsumptionUpdate StoreConsumption(List<ConsumptionRecord> consumptionRecords);


	ConsumptionUpdate StoreConsumption(ConsumptionRecord consumptionRecords);


}//end IConsumptionDAO