///////////////////////////////////////////////////////////
//  ICRUDDao.cs
//  Implementation of the Interface ICRUDDao
//  Generated by Enterprise Architect
//  Created on:      07-May-2021 2:59:26 PM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ICRUDDao<T, ID>
{
	int Count();

	void Delete(T entity);

	void DeleteAll();

	void DeleteById(ID id);

	bool ExistsById(ID id);

	IEnumerable<T> FindAll();

	IEnumerable<T> FindAllById(IEnumerable<ID> ids);

	T FindById(ID id);

	void Save(T entity);

	void SaveAll(IEnumerable<T> entities);

}//end ICRUDDao