///////////////////////////////////////////////////////////
//  IAuditReq.cs
//  Implementation of the Interface IAuditReq
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:23 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common_Project.Classes;

namespace Common_Project.DistributedServices
{
    public interface IAuditReq
    {
        List<AuditRecord> ReadAuditContnet();
    }//end IAuditReq
}