///////////////////////////////////////////////////////////
//  IDBReq.cs
//  Implementation of the Interface IDBReq
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:24 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common_Project.DistributedServices;
using System.ServiceModel;

namespace Common_Project.DistributedServices
{
    [ServiceContract]
    public interface IDBReq : IAuditReq, IConsumptionReq, IFileReq, IGeographyReq
    {

    }//end IDBReq
}
