///////////////////////////////////////////////////////////
//  IGeographyReq.cs
//  Implementation of the Interface IGeographyReq
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:24 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common_Project.Classes;
using CacheControler_Project.Enums;

namespace Common_Project.DistributedServices
{


	public interface IGeographyReq
	{

		/// 
		/// <param name="oldID"></param>
		/// <param name="newID"></param>
		EUpdateGeoStatus GeoEntityUpdate(string oldID, string newID);

		/// 
		/// <param name="gRecord"></param>
		bool GeoEntityWrite(GeoRecord gRecord);

		List<GeoRecord> ReadGeoContent();
	}//end IGeographyReq
}