///////////////////////////////////////////////////////////
//  IUIOps.cs
//  Implementation of the Interface IUIOps
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:24 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using CacheControler_Project.Enums;
using Common_Project.Classes;
using FileControler_Project.Enums;
using UI_Project.ClientServices;

namespace UI_Project.Classes
{
    public interface IUIOps:IFunctionalReq
    {

        List<AuditRecord> GetAuditEntities();

        List<string> GetGeographicEntities();

        /// 
        /// <param name="readReq"></param>
        Tuple<EConcumptionReadStatus, List<ConsumptionRecord>> InitConsumptionRead(DSpanGeoReq dSpanGeoReq);
        /// 
        /// <param name="filePath"></param>
        /// <param name="dataType"></param>
        EFileLoadStatus InitFileLoad(string filePath, ELoadDataType dataType);

        /// 
        /// <param name="gEntity"></param>
        EPostGeoEntityStatus PostGeoEntitiy(GeoRecord gEntity);

        /// 
        /// <param name="name"></param>
        EUpdateGeoStatus UpdateGeoEntity(string oldName, string newName);

        bool DBReconnect();

    }//end IUIOps
}