///////////////////////////////////////////////////////////
//  AuditDAOImpl.cs
//  Implementation of the Class AuditDAOImpl
//  Generated by Enterprise Architect
//  Created on:      07-May-2021 2:59:23 PM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class AuditDAOImpl : IAuditDAO {

	public AuditDAOImpl(){

	}

	~AuditDAOImpl(){

	}

}//end AuditDAOImpl