///////////////////////////////////////////////////////////
//  GeographyDaoImpl.cs
//  Implementation of the Class GeographyDaoImpl
//  Generated by Enterprise Architect
//  Created on:      07-May-2021 2:59:26 PM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class GeographyDaoImpl : IGeographyDAO {

	public GeographyDaoImpl(){

	}

	~GeographyDaoImpl(){

	}

}//end GeographyDaoImpl