///////////////////////////////////////////////////////////
//  IConsumptionRead.cs
//  Implementation of the Interface IConsumptionRead
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:24 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common_Project.Classes;

namespace CacheControler_Project.Services
{
    public interface IConsumptionRead
    {

        /// 
        /// <param name="dSpanGeoReq"></param>
        int DSpanGeoConsumptionRead(DSpanGeoReq dSpanGeoReq);
    }//end IConsumptionRead
}