using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FileControler_Project.Services
{
    ///////////////////////////////////////////////////////////
    //  IFControlerOps.cs
    //  Implementation of the Interface IFControlerOps
    //  Generated by Enterprise Architect
    //  Created on:      28-Apr-2021 10:30:24 AM
    //  Original author: Ugljesa
    ///////////////////////////////////////////////////////////

    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.IO;
    using Common_Project.Classes;
    using FileControler_Project.Enums;

    public interface IFControlerOps
	{

		/// 
		/// <param name="path"></param>
		/// <param name="dataType"></param>
		Tuple<EFileLoadStatus, ConsumptionUpdate> LoadFileStoreDB(string path, ELoadDataType dataType);
	}//end IFControlerOps
}
