
CREATE TABLE GEORECORD
(
	GID   varchar(10) NOT NULL,				
	GName varchar(10) NOT NULL,
	CONSTRAINT GRECORD_PK PRIMARY KEY(GID)	
	
);
commit;

CREATE TABLE EES_RECORD
(
	RECID      int NOT NULL,	
	TIME_STAMP varchar(20) NOT NULL,
    RTYPE      varchar(5)  NOT NULL,
    
	CONSTRAINT EES_RECORD_PK PRIMARY KEY(RECID),                          
    
    CONSTRAINT TYPE_DOM_CHK  CHECK (RTYPE in ('CR', 'AR')),
    CONSTRAINT RECID_CHK     CHECK (RECID >=0)
	
);
commit;

CREATE TABLE
(
    CONSTRAINT EES_RECORD_R_FK FOREIGN KEY REFERENCES EES_RECORD(RECID),
    CONSTRAINT EES_RECORD_G_FK FOREIGN KEY REFERENCES GRECORD(GNAME),
);
commit;

CREATE TABLE CONSUMPTION_RECORD
(
    MWH int NOT NULL,
    
    RECID_AST int NOT NULL REFERENCES EES_RECORD(RECID),
    PRIMARY KEY(RECID_AST)
);
commit;

CREATE TABLE AUDIT_RECORD
(
    DUPVAL int,
    
    EES_RECORD_AST int NOT NULL REFERENCES EES_RECORD(RECID),
    PRIMARY KEY(EES_RECORD_AST)
);
commit;