///////////////////////////////////////////////////////////
//  InitData.cs
//  Implementation of the Class InitData
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:24 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UI_Project.Classes
{

    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.IO;
    using Common_Project.Classes;

	namespace UI_Project.Classes
    {

   

	public class InitData
	{

		private AuditRecord auditRecords;
		private GeoRecord geoRecords;

		public InitData()
		{

		}

		~InitData()
		{

		}

		public int AuditRecord()
		{

			return 0;
		}

		public int GeoRecord()
		{

			return 0;
		}

	}//end InitData
}
}