///////////////////////////////////////////////////////////
//  EPostGeoEntityStatus.cs
//  Implementation of the Enumeration EPostGeoEntityStatus
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:23 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace CacheControler_Project.Enums
{
    public enum EPostGeoEntityStatus : int
    {

        Success,
        DBWriteFailed,
        DBWriteAborted,
        OutOfMemory,

    }//end EPostGeoEntityStatus
}