///////////////////////////////////////////////////////////
//  AuditService.cs
//  Implementation of the Class AuditService
//  Generated by Enterprise Architect
//  Created on:      07-May-2021 2:59:24 PM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common_Project;
using Common_Project.Classes;

public class AuditService {

	private IAuditDAO m_IAuditDAO;

	public AuditService(){

	}
	~AuditService(){

	}

	public List<AuditRecord> HandleReadAuditAll(){

		return null;
	}

}//end AuditService