///////////////////////////////////////////////////////////
//  ConsumptionService.cs
//  Implementation of the Class ConsumptionService
//  Generated by Enterprise Architect
//  Created on:      07-May-2021 2:59:25 PM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common_Project.Classes;

public class ConsumptionService {

	public IConsumptionDAO m_IConsumptionDAO = new ConsumptionDAOImpl();

	public ConsumptionService(){

	}

	~ConsumptionService(){

	}

	/// 
	/// <param name="countryID"></param>
	public List<ConsumptionRecord> HandleGetByCountry(string countryID) { 
		return m_IConsumptionDAO.FindByCountry(countryID);
	}

	public List<ConsumptionRecord> HandleGetByCountryAndDate(string countryID, string targetTimestamp){
		return m_IConsumptionDAO.FindByCountryAndDate(countryID, targetTimestamp);
	}

	/// 
	/// <param name="from"></param>
	/// <param name="till"></param>
	public List<ConsumptionRecord> HandleGetByCountryAndDatespan(string gID, string fromTimestamp, string tillTimestamp){
		return m_IConsumptionDAO.FindByCountryAndDatespan(gID, fromTimestamp, tillTimestamp);
	}

	public List<ConsumptionRecord> HandleGetByGeographyAndAfterDate(string gID, string from){
		return m_IConsumptionDAO.FindByGeographyAndAfterDate(gID, from);
	}

	public List<ConsumptionRecord> HandleGetByGeographyAndBeforeDate(string targetGID, string targetTimestamp){
		return m_IConsumptionDAO.FindByGeographyAndBeforeDate(targetGID, targetTimestamp);
    }

	/// 
	/// <param name="consumptionRecords"></param>
	public ConsumptionUpdate HandleStoreConsumption(List<ConsumptionRecord> consumptionRecords)
	{
		m_IConsumptionDAO.StoreConsumption(consumptionRecords);
		return null;
	}

	public ConsumptionUpdate HandleStoreConsumption(ConsumptionRecord consumptionRecords)
	{
		m_IConsumptionDAO.StoreConsumption(consumptionRecords);
		return null;
	}

	public List<ConsumptionRecord> HandleFindConsumptionAll()
	{
		return (List<ConsumptionRecord>)m_IConsumptionDAO.FindAll();
	}

}//end ConsumptionService