///////////////////////////////////////////////////////////
//  GeographyService.cs
//  Implementation of the Class GeographyService
//  Generated by Enterprise Architect
//  Created on:      07-May-2021 2:59:26 PM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common_Project.Classes;

public class GeographyService {

	public IGeographyDAO m_IGeographyDAO;

	public GeographyService(){

	}

	~GeographyService(){

	}

	public List<GeoRecord> HandleReadAll(){

		return null;
	}

	/// 
	/// <param name="id"></param>
	/// <param name="name"></param>
	public int HandleSignleGeoWrite(string id, string name){

		return 0;
	}

	/// 
	/// <param name="oldID"></param>
	/// <param name="newID"></param>
	public bool HandleSingleGeoUpdate(string oldID, string newID){

		return false;
	}

}//end GeographyService