///////////////////////////////////////////////////////////
//  EConcumptionReadStatus.cs
//  Implementation of the Enumeration EConcumptionReadStatus
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:23 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace CacheControler_Project.Enums
{
    public enum EConcumptionReadStatus : int
    {

        DBReadSuccess,
        DBReadFailed,
        CacheReadSuccess

    }//end EConcumptionReadStatus
}