///////////////////////////////////////////////////////////
//  IConsumptionRead.cs
//  Implementation of the Interface IConsumptionRead
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2021 10:30:24 AM
//  Original author: Ugljesa
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common_Project.Classes;
using CacheControler_Project.Enums;

namespace CacheControler_Project.Services
{
    public interface ICacheOps
    {

        /// 
        /// <param name="dSpanGeoReq"></param>
        Tuple<EConcumptionReadStatus, List<ConsumptionRecord>> DSpanGeoConsumptionRead(DSpanGeoReq dSpanGeoReq);

        bool DBTryReconnect();

        EPostGeoEntityStatus AddNewGeoEntity(GeoRecord geoRecord);

        bool ConsumptionUpdateHandler(string timeStampBase, ConsumptionUpdate update);

        EGeoRecordStatus ContainsGeo(GeoRecord geoRecord);

        EUpdateGeoStatus UpdateGeoEntity(string oldName, string newName);
    }//end IConsumptionRead
}